### ISSUE TITLE
Issue when mapping peptides to uniprot non-base isoforms

### ISSUE THREAD

**Issue by FFroehlich** [indralab/protmapper#18]
```
from protmapper import ProtMapper
pm = ProtMapper()
pm.map_peptide('Q8N3V7-2', 'LPAGPSSCTSPRS', 7)
```
correctly returns the site position `834`, but 

```
pm.map_peptide_to_human_ref('Q8N3V7-2', 'uniprot', 'LPAGPSSCTSPRS', 7)
```
fails with
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-240-2d6dd5f8ce0d> in <module>
      1 pm.map_peptide('Q8N3V7-2', 'LPAGPSSCTSPRS', 7)
----> 2 pm.map_peptide_to_human_ref('Q8N3V7-2', 'uniprot', 'LPAGPSSCTSPRS', 7)

/usr/local/lib/python3.7/site-packages/protmapper/api.py in map_peptide_to_human_ref(prot_id, prot_ns, peptide, site_pos)
    590                                                 prot_id.split('-')[1] != '1':
    591             raise ValueError("Protein ID passed in appears to be a "
--> 592                              "non-reference isoform: %s" % prot_id)
    593         # Get Uniprot ID and gene name
    594         up_id = _get_uniprot_id(prot_id, prot_ns)

ValueError: Protein ID passed in appears to be a non-reference isoform: Q8N3V7-2
```
which seems to be simply due to the unnecessary check whether one is requesting the sequence for the base isoform: `len(prot_id.split('-')) != 1 and prot_id.split('-')[1] != '1'`

**Comment by bgyori** [comment]
I think this is intentional since the protmapper isn't set up to map sites onto non-reference isoforms, hence the ValueError when such an isoform is detected.

**Comment by FFroehlich** [comment]
Hmm, I am not sure I understand. Doesn't the first example with `pm.map_peptide` show that the functionality is actually supported? `ProtMapper.map_to_human_ref` also seems to be able to handle isoform specific mapping.

**Comment by johnbachman** [comment]
The idea here is that you have a dataset where the peptide has been localized to a protein, but the Uniprot ID given may be for a specific isoform for that gene. So what you provide here to the function is not the Uniprot ID listed in the dataset (which may be isoform specific) but instead either 1) the gene name for the protein, which is likely in the dataset somewhere, or 2) the Uniprot ID of the reference isoform, which 99% of the time can be obtained by stripping of the "-x" suffix from the Uniprot ID.

**Comment by FFroehlich** [comment]
I think that pretty much describes what I am trying to do:

The dataset contains an entry `sp|Q8N3V7-2|SYNPO_HUMAN` at position `834` with motif `LPAGPSSCTSPRS` (technically not the peptide, but just the site+-6AA, but it should be possible to it equivalently).

I could validate that site using `pm.map_to_human_ref('Q8N3V7-2', 'uniprot', 'S', 384)`, which will tell me that this is indeed a valid site. I don't know though whether this site is isoform specific or whether it could be mapped back to the reference isoform. To assess this I can try `pm.map_peptide_to_human_ref('Q8N3V7', 'uniprot', 'LPAGPSSCTSPRS', 7)`, which will not return any mapping. This indicates that this particular site is specific to isoform 2. Technically, I am now done because I know that the site is valid on isoform 2, but let's assume for the moment that it was not a valid site. What I now probably want to do is call `pm.map_peptide_to_human_ref('Q8N3V7-2', 'uniprot', 'LPAGPSSCTSPRS', 7)` to see whether it is still possible to remap the site to the isoform sequence or not.

**Comment by johnbachman** [comment]
I see. Generally it is a given that the position reported in the dataset is valid for the (possibly isoform-specific) ID given. If I wanted to be sure, I would normally use `protmapper.uniprot_client.verify_location()` to check if a site was valid for the given protein ID, but this only looks at a single residue. To get the reference sequence position, I would use `map_to_human_ref`, and if the peptide is not found, I would fall back on the ID reported in the dataset.

As you can see by looking at the code for `map_peptide_to_human_ref`, the function is mainly a wrapper around `map_peptide` that deals with getting the canonical uniprot ID from the gene name.

**Comment by FFroehlich** [comment]
Okay, I guess that makes sense, thanks for the explanation!
