### ISSUE TITLE
Add entrez identifier conversions

### ISSUE THREAD

**Issue by cthoyt** [indralab/protmapper#28]
I think it would be very helpful to have functions to get the UniProt identifier for a given entrez identifier, and get the entrez identifier for a given UniProt identifier

**Comment by bgyori** [comment]
This is trivial to add since the resource file already contains these IDs, they are just not exposed via the API for conversion. We could add a simple ID conversion utility in protmapper to map at least across the ID types that are already covered by the existing resource files.

**Comment by bgyori** [comment]
Note that he resource file currently only contains Entrez mappings for _human_ genes/proteins, which is the main focus of protmapper anyway, is that sufficient for what you want to do?

**Comment by cthoyt** [comment]
Thanks, @bgyori! I'm glad this was little effort. I think I would want to convert between non-human proteins at some point, but that's not in scope for ProtMapper right now so this is sufficient
